### ISSUE TITLE
python sdk crashes when call to cerbos returns http 400

### ISSUE THREAD

**Issue by jesumyip** [cerbos/cerbos-sdk-python#20]
https://github.com/cerbos/cerbos-sdk-python/blob/854c11629830d7b4a9a1be7cf0f3d7fea6053a22/cerbos/sdk/_sync/client.py#L236

The line of code above crashes if the call to `check_resources` on line 229 returns an error. It's probably more prudent to check the return state first before executing line 236.

**Comment by charithe** [comment]
Well, this is intentional. Any none 2xx response will raise an exception: https://github.com/cerbos/cerbos-sdk-python/blob/854c11629830d7b4a9a1be7cf0f3d7fea6053a22/cerbos/sdk/_async/client.py#L127-L131
