### ISSUE TITLE
Add types-protobuf to requirements

### ISSUE THREAD

**Issue by j-riebe** [cerbos/cerbos-sdk-python#41]
While working with the grpc client, I noticed that pyCharm doesn't recognize the protobuf types. 
This makes it very uncomfortable to use resources with schemas that require to instantiate `Value` objects.

After some digging, I managed to solve this issue by installing the protobuf stubs `types-protobuf`.
The developer experience for working with the grpc client could be improved, if `types-protobuf` would be installed along with the SDK.

**Comment by Sambigeara** [comment]
Hi, thanks for raising.

> pyCharm doesn't recognize the protobuf types.

What do you mean by this? That you're missing language features (auto completion, go to definition etc)? If so, which types are affected?

On my local set up, I'm seeing all the features I'd expect working on the `struct_pb2.Value` type.

**Comment by Sambigeara** [comment]
Thanks for sharing. Interestingly, I get the expected behaviour using either [pyright](https://github.com/microsoft/pyright) or [python-lsp](https://github.com/python-lsp/python-lsp-server) with nvim's native LSP client (the following shows the former):

<img width="812" alt="image" src="https://github.com/cerbos/cerbos-sdk-python/assets/11599982/6078485c-8189-4174-8897-7070fbd6e94f">

Do you know which language servers (or otherwise) you're both using?

**Comment by j-riebe** [comment]
Thanks again for the fast reply.

AFAIK pyCharm (IntelliJ is basically the same) has its own type checker (its listed beside pyright in the [typeshed](https://github.com/python/typeshed#using) package, which is also the source of the `types-protobuf` stubs).

Could it be possible that your setup somehow has access to the protobuf stubs without explicitly installing them (e.g. globally shared stubs / cached stubs from another project)? 
This should be verifiable easily by using the "Go to definition" functionality and checking whether the file is located in the venv associated with the project or somewhere else.

And do you end up with the same file I added to the detail section in the answer above? That way I could check if my installation is somehow messed up.

**Comment by Sambigeara** [comment]
> Could it be possible that your setup somehow has access to the protobuf stubs without explicitly installing them (e.g. globally shared stubs / cached stubs from another project)?

Oh you've hit the nail on the head there 😄: `.../typeshed-fallback/stubs/...`.

I'll add these in explicitly - many thanks!

**Comment by j-riebe** [comment]
Great! Much appreciated 👍 

BTW in the meantime I found out, that pyCharm also comes with its own version of `typeshed`.
Unfortunately, it doesn't contain the protobuf stubs for whatever reason.
