### ISSUE TITLE
Vendoring google protos causes collision

### ISSUE THREAD

**Issue by kojiromike** [cerbos/cerbos-sdk-python#44]
We tried to install the cerbos-sdk-python in a project that already uses google protobufs, and got this message:

```
  • Installing cerbos (0.10.1): Installing...
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/google/api/annotations_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/google/api/field_behavior_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/google/api/http_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/google/api/visibility_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/protoc_gen_openapiv2/options/annotations_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/protoc_gen_openapiv2/options/annotations_pb2.pyi over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/protoc_gen_openapiv2/options/annotations_pb2_grpc.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.py over existing file
  Installing $HOME/Library/Caches/pypoetry/virtualenvs/preferences-service-oGN0U57V-py3.11/lib/python3.11/site-packages/protoc_gen_openapiv2/options/openapiv2_pb2.pyi over existing file
```

Would it be possible for cerbos-sdk-python to vendor the google protos inside a namespace package, so that they don't collide with the protos provided directly by Google?

**Comment by Sambigeara** [comment]
Hey, thanks for raising.

I avoided this approach when I reworked the SDK fairly recently, due to issues with auto-generated import paths and ad-hoc namespace collisions. I can't remember the specifics, but I did write about the experience [here](https://cerbos.dev/blog/from-http-to-grpc-trials-tribulations-and-triumphs-of-porting-our-python-sdk). I was reluctant to start playing with `PYTHONPATH` and ultimately conceded and approached it [the Google way](https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-263772124).

That said, I probably didn't give this approach enough of a looking during the above. We're heads down in some other work at the mo but I'll add this to my backlog to explore after!

Just so I fully understand, is the issue that the project in question is already vendoring the google protos at the top level?

**Comment by kojiromike** [comment]
> Just so I fully understand, is the issue that the project in question is already vendoring the google protos at the top level?

That _would_ cause the problem, but to be sure, it would still cause the problem even if the package just declares google protos as a dependency and does not vendor it. Here's a script that demonstrates the problem.


```bash
#!/usr/bin/env bash

# export PIP_DISABLE_PIP_VERSION_CHECK=1

main() {
  local tempdir="${1:-cerbos-proto-clobber-test}"
  mkdir -p "$tempdir"
  cd "$tempdir" || return 
  # Use poetry because pip doesn't tell you when dependencies have a conflict.
  # https://github.com/pypa/pip/issues/4625
  {
    echo '[build-system]'
    echo 'requires = ["poetry-core"]'
    echo 'build-backend = "poetry.core.masonry.api"'
    echo
    echo '[tool.poetry]'
    echo 'name = "cerbos-proto-clobber-test"'
    echo 'version = "0.1.0"'
    echo 'license = "MIT"'
    echo 'authors = []'
    echo 'description = "demo of https://github.com/cerbos/cerbos-sdk-python/issues/44"'
    echo 
    echo '[tool.poetry.dependencies]'
    echo 'python = "^3.11"'
  } > pyproject.toml

  poetry install --no-root
  poetry add googleapis-common-protos 
  poetry add cerbos
}


main "$@"
```

Note that due to pypa/pip#4625, it's harder to see the issue when using pip than when using poetry. The issue occurs regardless of which tool is used, though.

**Comment by kojiromike** [comment]
@Sambigeara I read your blog post – it was very informative, thanks for taking the time. It clearly describes the import issue of protocolbuffers/protobuf#1491, and I hope that the protocolbuffers will keep thinking about how to address that.

However, are you saying that fixing that issue is necessary for cerbos to avoid vendoring the google protos? If cerbos-sdk-python excluded the google protos from its own package, but made them instead a runtime dependency, they would be available to cerbos' grpc at the PYTHONPATH just as they are now, but there would be no filesystem conflict at install time.

I recently went through this de-vendoring process with our own protos, so I would be happy to help if I can.

**Comment by Sambigeara** [comment]
Thanks for the breakdown and example script - I was able to reproduce the issue 👍. It also helped remind me of the issue I experienced before:

If I remove the dependencies from the proto build command (removing the flag [here](https://github.com/cerbos/cerbos-sdk-python/blob/main/proto/generate_protos.sh#L12)) and install `protobuf` as a runtime dependency, the interpreter fails with something along the lines of:

```sh
$ pdm run pytest
ImportError while loading conftest '/Users/samuellock/cerbos/cerbos-sdk-python/tests/conftest.py'.
tests/conftest.py:11: in <module>
    from cerbos.sdk.grpc.client import AdminCredentials, AsyncCerbosAdminClient
cerbos/sdk/grpc/client.py:4: in <module>
    from cerbos.sdk._async._grpc import (
cerbos/sdk/_async/_grpc.py:16: in <module>
    from cerbos.engine.v1 import engine_pb2
cerbos/engine/v1/engine_pb2.py:17: in <module>
    from cerbos.schema.v1 import schema_pb2 as cerbos_dot_schema_dot_v1_dot_schema__pb2
cerbos/schema/v1/schema_pb2.py:16: in <module>
    from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
E   ModuleNotFoundError: No module named 'google.api'
```

Importing the protos explicitly means all the auto-generated import paths work as expected. Using runtime deps as above has me a little stumped.

Is this similar to the problem you solved? Would be keen to hear how you solved it if so.

**Comment by kojiromike** [comment]
I think you would need `googleapis-common-protos` instead of `protobuf` as a dependency. Perhaps both.

**Comment by Sambigeara** [comment]
Thanks, I got tangled there. Like you say, it seems to be as simple as tracking down all required dependencies (pre-compiled). ATM, some are more elusive than others, e.g. I can't find a pre-compiled version of [this particular module](https://github.com/googleapis/googleapis/blob/master/google/api/expr/v1alpha1/checked.proto). I'll have a dig.

**Comment by Sambigeara** [comment]
I'm not getting much further with this approach, unfortunately. Some compiled proto packages I found in pypi are one-off pushes from third parties, and therefore unmaintained. Others, I can't find at all (e.g. `google.api.expr` mentioned above).

Vendoring directly ultimately references [buf's repositories](https://github.com/cerbos/cerbos/blob/main/api/public/buf.yaml#L4-L7), which are actively maintained and therefore seem more reliable. In some cases, prioritising Cerbos' compiled protos makes sense, given that the third-party packages are likely obsolete and less adopted.

I'm reluctant to introduce any additional aggregated packages due to the additional maintenance layer.

I'm not sure how to solve this at the moment 🤔

**Comment by kojiromike** [comment]
Well, thanks for taking the time anyway. It's not a perfect solution, (and it's hardly your fault that python and protobufs interact this way) but have you considered making the grpc implementation itself optional? If you could ship the package with rest support only, without the protos, then folks would have a way to include the cerbos client without worry about that particular collision vector.

**Comment by Sambigeara** [comment]
This is on my radar, my focus is elsewhere in the short(/mid?) term but I'll circle back to this afterwards! Apologies if this is blocking.
